### ISSUE TITLE
部分任务点状态获取出现403错误

### ISSUE THREAD

**Issue by C315703603** [liuyunfz/chaoxing_tool#103]
![LN$ }$_V~8T{6X~1Q7O0433](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/1a7cc5d2-5e9e-48f2-b7d7-59ce0966d376)
修改完成等时长刷取后程序还是速刷，因为速刷最后是显示处理完了但是没刷上，而且容易触发反爬。
如果想等时长按顺序刷是还需要在哪里设置吗?

**Comment by liuyunfz** [comment]
应该是可以的呢，就是修改后程序需要重新启动，并不是热加载呢

**Comment by C315703603** [comment]
Uploading 1693828323687_batch.mp4…
如视频，最后也是速刷太快触发反爬，如果设置没问题的话，不会是我环境的问题吧，

**Comment by C315703603** [comment]
如视频，最后也是速刷太快触发反爬，如果设置没问题的话，不会是我环境的问题吧

https://github.com/liuyunfz/chaoxing_tool/assets/103497700/c11272ea-2ac1-444c-bf0b-805aa0a5281f

**Comment by liuyunfz** [comment]
你好，最新的版本已经添加了全局延时请求的功能，您可以再试试是否还会出现这个问题

**Comment by C315703603** [comment]
已经大概率不会触发反爬系统了，但是最后读取完课程的所有任务点后会直接显示该课程处理完成，并没有进行等时长的刷取，所有课程都是这样，如图。
![D{$L L0RUN9VE}{L0DI5W@J](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/25628624-61d7-43cc-9c24-f0f2c801ff1a)

**Comment by liuyunfz** [comment]
这是没读取到视频任务点，我迟点再去测试一下

**Comment by liuyunfz** [comment]
最新的commit已经修复了媒体资源读取，还烦请再测试一下

**Comment by C315703603** [comment]
![{F1KMU {9{ BE97W({L3BCW](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/635ced44-a93a-4b92-b6c8-cc51dd4d497f)
![V~XI}A@SOK34@UIBXMB6(ML](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/4fe25ae4-1654-4408-aa72-b8eaa6b21a9c)
会出现视频状态获取失败的情况

**Comment by C315703603** [comment]
是视频类型的，我后来把测验做完仅剩视频任务点的情况下还是如此，如下是其中一段。
2023-09-06 07:55:46.267 | DEBUG | utils:doGet:33 - Do Get to Url https://mooc1-1.chaoxing.com/ananas/status/f3af4ad6ee96bc5b11a34ea723f44e3f?k=&flag=normal&_dc=1600850935908
2023-09-06 07:55:46.267 | DEBUG | utils:doGet:33 - Do Get to Url https://mooc1.chaoxing.com/mycourse/studentstudyAjax?courseId=235123512&clazzid=78027062&chapterId=705061613&cpi=289979121&verificationcode=&mooc2=1
2023-09-06 07:55:46.911 | DEBUG | utils:doGet:33 - Do Get to Url https://mooc1.chaoxing.com/knowledge/cards?clazzid=78027062&courseid=235123512&knowledgeid=705061613&num=0&ut=s&cpi=289979121&v=20160407-1
2023-09-06 07:55:47.024 | ERROR | utils:doGet:46 - Get Url https://mooc1-1.chaoxing.com/ananas/status/f3af4ad6ee96bc5b11a34ea723f44e3f?k=&flag=normal&_dc=1600850935908 Error
 Url: https://mooc1-1.chaoxing.com/ananas/status/f3af4ad6ee96bc5b11a34ea723f44e3f?k=&flag=normal&_dc=1600850935908
Method: Get
Status: 403
2023-09-06 07:55:47.025 | ERROR | classis.Media.Video:get_status:32 - the JSON object must be str, bytes or bytearray, not NoneType
Exception in thread Thread-26 (run_video):
Traceback (most recent call last):
  File "C:\Users\31570\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\31570\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\31570\Downloads\Compressed\chaoxing_tool-master\functions\set_time\deal_time.py", line 42, in run_video
    raise RequestException("视频状态获取失败")
  File "C:\Users\31570\Downloads\Compressed\chaoxing_tool-master\classis\SelfException\__init__.py", line 18, in __init__
    self.text = html.text
AttributeError: 'str' object has no attribute 'text'
![Q`X5N8PC) MH7ZTX$W06IM](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/5e94a221-29ec-40ef-aa79-411eec4c5cd8)

**Comment by liuyunfz** [comment]
今天测试时偶然出现了一次，但当我再次重新运行程序后就没有报错了。现在的猜测是因为等时长刷取是启用的线程，可能线程并发导致的cookie冲突问题。不知道你那边再次运行是否是同一个视频任务报错？还是比较随机但是由于数量大导致每次都会报错

**Comment by C315703603** [comment]
基本上都是从第一个视频任务点开始就开始报错了，错误类型就和之前发的图一样。

**Comment by monkey5689** [comment]
> 基本上都是从第一个视频任务点开始就开始报错了，错误类型就和之前发的图一样。

我也是从第一个任务点开始就一直403了

**Comment by liuyunfz** [comment]
你好，最新的版本添加了单线程刷取选项以及线程的随机延迟启动。我这边测试了三次，分别如下：
1. 使用单线程模式，未出错
2. 使用多线程模式，第二个任务点报错
3. 使用随机延迟多线程模式，第一轮任务执行未出现报错
综上，烦请大家帮忙测试一下

**Comment by monkey5689** [comment]
> 你好，最新的版本添加了单线程刷取选项以及线程的随机延迟启动。我这边测试了三次，分别如下：
> 
> 1. 使用单线程模式，未出错
> 2. 使用多线程模式，第二个任务点报错
> 3. 使用随机延迟多线程模式，第一轮任务执行未出现报错
> 
> 综上，烦请大家帮忙测试一下

随机延迟在哪里设置？

**Comment by liuyunfz** [comment]
随机延迟默认启动的，如果是多线程

**Comment by liuyunfz** [comment]
看到近期大家没有继续反馈相关问题，如果以修复将在未来几日关闭本issue。如果仍有类似问题还烦请继续告知
