### ISSUE TITLE
出现了Method: Get Status: 202这个问题

### ISSUE THREAD

**Issue by 1642414488** [liuyunfz/chaoxing_tool#109]

**Comment by Kiwll** [comment]
作者你好，我遇到这两个问题，该怎么解决

| ERROR | 检测到不支持的任务点类型:workid

| ERROR | utils:doGet:46 - Get Url https://mooc1.chaoxing.com/mycourse/studentstudyAjax?courseId=237709014&clazzid=84370792&chapterId=705038278&cpi=283261694&verificationcode=&mooc2=1 Error
 Url: https://mooc1.chaoxing.com/antispiderShowVerify.ac
Method: Get
Status: 202
 | ERROR | 功能调用失败，请检查输入的功能序号
 | ERROR | __main__:<module>:125 - can only parse strings

**Comment by liuyunfz** [comment]
造成该问题的原因是访问超星速度太快触发了超星学习通的反爬虫系统。
解决办法请提高config.yml配置文件中的延迟时长，即Gloconfig下的delay中的time

**Comment by Kiwll** [comment]
> |错误 |检测到不支持的任务点类型：workID

那大佬这个问题该咱么解决呢

**Comment by liuyunfz** [comment]
> > |错误 |检测到不支持的任务点类型：workID
> 
> 那大佬这个问题该咱么解决呢
> 

这个其实不算报错，本程序本就不支持测验类型的任务点。尽管程序提示错误，但应该并不影响后续继续运行。
如果需要完成该类任务点可以尝试使用部分带搜题功能的油猴脚本

**Comment by Kiwll** [comment]
> > > |错误 |检测到不支持的任务点类型：workID
> > 
> > 
> > 那大佬这个问题该咱么解决呢
> 
> 这个其实不算报错，本程序本就不支持测验类型的任务点。尽管程序提示错误，但应该并不影响后续继续运行。 如果需要完成该类任务点可以尝试使用部分带搜题功能的油猴脚本
首先谢谢大佬，我明白您的意思，可是我目前使用有的视频任务点也会显示出这个问题，这个是什么原因呢

**Comment by Kiwll** [comment]
> 造成该问题的原因是访问超星速度太快触发了超星学习通的反爬虫系统。 解决办法请提高config.yml配置文件中的延迟时长，即Gloconfig下的delay中的time

| ERROR | utils:doGet:46 - Get Url https://mooc1-1.chaoxing.com/ananas/status/53b368dba31069a533d7ba42?k=&flag=normal&_dc=1600850935908 Error
 Url: https://mooc1-1.chaoxing.com/ananas/status/53b368dba31069a533d7ba42?k=&flag=normal&_dc=1600850935908
Method: Get
Status: 403
2023-10-16 16:14:04.891 | ERROR | classis.Media.Video:get_status:32 - the JSON object must be str, bytes or bytearray, not NoneType
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "C:\Users\k1561\Downloads\chaoxing_tool\main\functions\set_time\deal_time.py", line 42, in run_video
    raise RequestException("视频状态获取失败")
  File "classis\SelfException\__init__.py", line 18, in __init__
    self.text = html.text
AttributeError: 'str' object has no attribute 'text'
您好大佬，我将时间从0.5改成1后出现了这种错误怎么办啊

**Comment by liuyunfz** [comment]
这个大概率是多线程并发请求引起的，可以试试重新运行一次或者使用单线程模式(也在配置文件中可修改)。
