### ISSUE TITLE
[bug]无法正常退出，强制关闭后无法打开

### ISSUE THREAD

**Issue by cuo-ren** [liuyunfz/chaoxing_tool#128]
# 如图所示

<img width="874" alt="1" src="https://github.com/user-attachments/assets/cb483133-83ca-44e4-91e0-5484d7aebc09">

```
菜单
1. ✅ 一键完成课程中的任务节点
2. 📂 下载课程中的资源
3. 📜 刷取课程学习次数
4. ⏳ 刷取课程视频观看时长
5. 🔃 退出当前已登录账号
6. 💾 保存设置并退出本程序

请输入您要使用功能的序号:6
19:02:50 | ERROR | 功能调用失败，请检查输入的功能序号
2024-10-14 19:02:50.527 | ERROR | __main__:<module>:125 - name 'exit' is not defined
```

## 强制退出后报错如下

<img width="867" alt="屏幕截图 2024-10-14 190536" src="https://github.com/user-attachments/assets/f9c2abb6-5666-4c4a-a8c7-187c3e6794aa">

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\liuyun\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "classis\User\__init__.py", line 9, in <module>
    from ..Course import Course
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\liuyun\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "classis\Course\__init__.py", line 10, in <module>
    from utils import doGet, xpath_first, doPost
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\liuyun\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "utils.py", line 14, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
[1528] Failed to execute script main
```

**Comment by cuo-ren** [comment]
现在强制关闭不会报错了，但仍然无法正常退出

**Comment by cuo-ren** [comment]
建议导入sys `import sys` ，然后将程序中所有的`exit()`或`exit(0)`替换为`sys.exit()`或`sys.exit(0)`
