### ISSUE TITLE
刷时长似乎会溢出

### ISSUE THREAD

**Issue by wzcv** [liuyunfz/chaoxing_tool#23]
Traceback (most recent call last):
  File "E:\CHAOXING\chaoxing.py", line 953, in <module>
    Menu().run()
  File "E:\CHAOXING\chaoxing.py", line 924, in run
    action()
  File "E:\CHAOXING\chaoxing.py", line 872, in misson_5
    isThread = get_task_status(course_dict[i + 1][1])
  File "E:\CHAOXING\chaoxing.py", line 613, in get_task_status
    medias_text = medias_HTML.xpath("//script[1]/text()")[0]
IndexError: list index out of range

**Comment by liuyunfz** [comment]
您好，能询问下你使用的版本嘛，理论上这条代码`medias_text = medias_HTML.xpath("//script[1]/text()")[0]`已经在https://github.com/liuyunfz/chaoxing_tool/commit/19f459002953f46c5de538ce6d75254eddf33a50 版本后被我添加了异常捕获，不会出现终止程序运行的问题。

**Comment by wzcv** [comment]
谢谢大佬，试了下最新版确实可以了
