### ISSUE TITLE
请问IndexError: list index out of range报错如何处理，谢谢

### ISSUE THREAD

**Issue by 19819068211** [liuyunfz/chaoxing_tool#24]
Traceback (most recent call last):
  File "chaoxing.py", line 987, in <module>
    Menu().run()
  File "chaoxing.py", line 958, in run
    action()
  File "chaoxing.py", line 738, in misson_1
    deal_course_select(course_dict[course_item][1])
  File "chaoxing.py", line 234, in deal_course_select
    deal_misson(chapter_mission, new_url_dict["cpi"], 0)
  File "chaoxing.py", line 441, in deal_misson
    cardcount = int(read_cardcount(courseId, clazzId, chapterId, class_cpi))
  File "chaoxing.py", line 302, in read_cardcount
    return rsp_HTML.xpath("//input[@id='cardcount']/@value")[0]
IndexError: list index out of range

**Comment by liuyunfz** [comment]
你好，新版本 https://github.com/liuyunfz/chaoxing_tool/commit/0403f87ad298612348418ac20794a319a82a4eac 暂时隐藏了这个错误并输出了一些相关信息。如果这样影响了你的正常使用，麻烦您提供给我新版输出的相关错误信息，以协助我寻找问题所在，感谢

**Comment by 19819068211** [comment]
没有问题了，太棒了，谢谢
