### ISSUE TITLE
将desktop打包为exe后报错

### ISSUE THREAD

**Issue by NAILIANGCHI** [liuyunfz/chaoxing_tool#38]
Traceback (most recent call last):
  File "chaoxing01.py", line 1023, in <module>
  File "chaoxing01.py", line 1015, in start
  File "chaoxing01.py", line 893, in before_start
  File "tkinter\__init__.py", line 2071, in wm_iconbitmap
_tkinter.TclError: bitmap "chaoxing_icon.ico" not defined

**Comment by NAILIANGCHI** [comment]
![image](https://user-images.githubusercontent.com/85297838/167650369-6bf1a2fb-78cb-416d-b546-298a869f0ca9.png)

**Comment by NAILIANGCHI** [comment]
这是来自QQEmail的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by NAILIANGCHI** [comment]
> 把图标复制进打包生成exe的同级目录里

对了，在pycharm中调试运行正常

**Comment by SongZihui-sudo** [comment]
```
        cd desktop
	pyinstaller -F -w chaoxing.py
	copy ".\chaoxing_icon.ico" ".\dist\"
```

**Comment by SongZihui-sudo** [comment]
在desktop文件夹，打开cmd：  `pyinstaller -F -w chaoxing.py`,在复制图标到exe的目录`copy ".\chaoxing_icon.ico" ".\dist\"`

**Comment by NAILIANGCHI** [comment]
> 懂了感谢

**Comment by SongZihui-sudo** [comment]
或者重新clone一下，加了一个批处理

**Comment by NAILIANGCHI** [comment]
这是来自QQEmail的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
